# The predict price lambda is deployed via a container image due to the size of the dependencies. This pipeline downloads
# the latest ML model, bakes it into an image and then deploy the image to AWS ECR.
# It takes a bit more time and resources to build and upload the Docker image so I've separated it from the other CD
# steps.
name: build_predict_price

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::623791025140:role/fuel-forecast-cicd
          aws-region: ap-southeast-2
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 623791025140.dkr.ecr.ap-southeast-2.amazonaws.com
      - name: Download current fuel forecast model
        run: aws s3 cp s3://unclechris-fuel-forecast-storage/model.pkl ./py/functions/predict_price/model.pkl
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: "./py/functions/predict_price"
          push: true
          tags: 623791025140.dkr.ecr.ap-southeast-2.amazonaws.com/fuel-price:latest
      - name: Re-deploy lambda with new version of image
        run: aws lambda update-function-code --function-name predict_price --image-uri 623791025140.dkr.ecr.ap-southeast-2.amazonaws.com/fuel-price:latest
